### ISSUE TITLE
Dynamically changing the .SwipeViewsTab color

### ISSUE THREAD

**Issue by vgoklani** [damusnet/react-swipe-views#10]
Is there a simple way of changing the .SwipeViewsTab color?

It's ignoring all my style={} commands,

<SwipeViews style={..}>
...
</SwipeViews>

I'm guessing that there should be a way of changing the style arguments

**Comment by jackyon** [comment]
+1

**Comment by damusnet** [comment]
For now, all the styling is in a separate css file, that you can simply override. Take a look at the [demo](http://damusnet.github.io/react-swipe-views/). It's true that more and more projects are styling components inline or with a tighter coupling, but I am still undecided about that.

**Comment by vgoklani** [comment]
It's just much simper to pass in CSS attributes directly (in-line). For me specifically, I use this component in two separate places, with slightly different attributes, so being stuck with 1 set of CSS attributes (hard-coded in a file) ends up being limiting.
