### ISSUE TITLE
Unable to load CSS properties

### ISSUE THREAD

**Issue by divyenduz** [damusnet/react-swipe-views#12]
I tried loading this using webpack. It shows like 
![bug](https://cloud.githubusercontent.com/assets/746482/11950902/cba65c12-a8b2-11e5-8965-40eaf600efdd.png)

I tried to include CSS manually by using link tag from node_modules. Still, it was the same. 

Any pointers on how do I make this work with webpack ?

**Comment by divyenduz** [comment]
It worked after I added the CSS manually to html. I think this can be closed as the issue is in my implementation of webpack and I am not sure if that should be included in docs

**Comment by divyenduz** [comment]
Have you tried including this from npm instead of bower. I think there are issues with csss in that case

**Comment by damusnet** [comment]
There are two examples in the lib, one with bower, the other one with npm. Also, I only use npm nowadays. In any case, this would probably indicate a problem with the build steps, and not related to the lib itself.

**Comment by vgoklani** [comment]
I have the same issue, I use NPM, and had to manually link the CSS file.

**Comment by damusnet** [comment]
This is actually the expected behavior. I'm considering a tighter coupling between CSS and JS, but each solution has it's pros and cons.

**Comment by divyenduz** [comment]
How about CSS modules ? 
https://github.com/css-modules/css-modules

I am working on a fork of this library, (https://github.com/divyenduz/react-tab-layout), I am considering to use css modules.

What are the other options you considered ?

Thanks,

**Comment by damusnet** [comment]
The problem with this approach is that you can only use it with webpack as far as I know.
People with gulp or grunt or other build methods would not be able to use this lib anymore.

Another option is to put every style inline. [Material UI](https://github.com/callemall/material-ui/blob/master/src/SelectField/SelectField.jsx#L196) does this, but I have found it harder to read and use. I still have to dig into it to know what the best practice is those days.

**Comment by divyenduz** [comment]
Yes, writing inline is not the tidiest. Also, would you consider a PR so that this component supports dynamically changing children, as of now it calculates the page width based on the initial number of children it had and so, if the number of children change the dimensions break. I solved this in my ( https://github.com/divyenduz/react-tab-layout ) version of this component by maintaining the number of children in state and updating it when new props are received. Any opinion on that approach ?
