### ISSUE TITLE
can you update the examples demo for react-router v2.0.xxx

### ISSUE THREAD

**Issue by Saajan** [damusnet/react-swipe-views#18]
Since there are some breaking changes in new react-router . Im getting some warnings while using this component. Thanks in advance

**Comment by ponty96** [comment]
@Saajan  can u please post the warnings you're getting

**Comment by Saajan** [comment]
during initial load :
Warning: Failed Context Types: Invalid context `router` of type `object` supplied to `xxx`, expected `function`. 

while swiping the content :
Uncaught TypeError: search.substring is not a function

**Comment by adcooley** [comment]
+1 here, I'm on the latest and greatest react-router as well. Seeing those same warnings

**Comment by adcooley** [comment]
@ponty96 @Saajan this was actually causing problems for me (the swipe-to-navigate wouldn't snap to the new route). I managed to fix it (will submit a PR) but there's a new warning because I reverted to using `context.history` instead of `context.router`

**Comment by adcooley** [comment]
#29

**Comment by Saajan** [comment]
Thanks for the help @adcooley ... cheers
