### ISSUE TITLE
I want to use this as a separate component. Gives an Error

### ISSUE THREAD

**Issue by tushartuteja** [damusnet/react-swipe-views#23]
My code is the following.

```
var React = require('react');


var SwipeViews = require('react-swipe-views');
var Tabs = React.createClass({

  componentWillMount : function(){
    this.setState({
      index: 0
    });
  },


  _onIndexChange(selectedIndex) {
    this.setState({
      index: selectedIndex
    });
  },

  render() {
    return (
      <SwipeViews selectedIndex={this.state.index} onIndexChange={this._onIndexChange.bind(this)}>
        <div title="Intro">
          <h1>A React component for binded Tabs and Swipeable Views</h1>
          <p>See <a href="http://developer.android.com/design/patterns/swipe-views.html">
          Swipe Views</a> on the Android Design Patterns website to understand the desired effect.</p>
          <p>This demo is best viewed on a touch enabled device (real or emulated).</p>
          <p style={{textAlign: 'center'}}><a href="https://github.com/damusnet/react-swipe-views"><button>Download</button></a></p>
        </div>
        <div title="Code">
          <h1>Gist</h1>
        </div>
        <div title="Thanks">
          <ul id="thanks">
            <li><a href="https://twitter.com/davidbruant">David Bruant</a> for making me believe in JavaScript</li>
            <li><a href="http://facebook.github.io/react/">React</a> for being awesome</li>
            <li><a href="http://babeljs.io/">Babel</a> for removing so much pain from transpiling/compiling/bundling</li>
            <li><a href="https://github.com/gaearon">Dan Abramov</a> for all the useful ressources, in this case <a href="https://github.com/gaearon/react-hot-boilerplate">React Hot Boilerplate</a></li>
            <li><a href="https://github.com/TheSeamau5">Hassan Hayat</a>'s <a href="https://github.com/TheSeamau5/swipe-pages">Swipe Pages WebComponent</a> for inspiration</li>
            <li><a href="https://github.com/ferrannp">Ferran Negre</a> for helping me debug</li>
          </ul>
          <p style={{textAlign: 'center'}}><a href="#" onClick={(e) => {
            e.preventDefault();
            this.setState({
              index: 0
            });
          }}><button>Back to Intro</button></a></p>
        </div>
      </SwipeViews>
    );
  }
});

module.exports = `Tabs;`

```

then  I am using this in the following

`<div><h1> Property Name {this.props.params.property_uuid}</h1>
      <Tabs></Tabs></div>`

this is showing up like the following

![image](https://cloud.githubusercontent.com/assets/5651179/14503312/3b7ee964-01cd-11e6-9eb5-204585e27f99.png)

**Comment by CaptainN** [comment]
You must link the css file.

**Comment by tushartuteja** [comment]
Hi,
I am getting the following error, and it still doesn't work.

SwipeViews.js:142 Uncaught TypeError: Cannot read property 'to' of undefined

**Comment by tushartuteja** [comment]
![image](https://cloud.githubusercontent.com/assets/5651179/14521189/dc31181e-0245-11e6-9ec7-0a7fd4164d7f.png)

this is how it looks now.

**Comment by damusnet** [comment]
Do you have React Router in your project?
Try setting a prop `to={null}` on your title divs (like `<div title="Intro" to="intro">`).

**Comment by tushartuteja** [comment]
Yes, there is a react router in my project which manages the main app. 
This is supposed to be a subview. 
I tried setting to={null}, like the following
        <div title="Code" to={null}>
It still doesn't work. The problem I am having is that, the view are working fine, I have three swipe views but the content in all the views is being showed up in the first view.

**Comment by tushartuteja** [comment]
Whenever i swipe, I get this error
SwipeViews.js:165 Uncaught TypeError: Cannot read property 'to' of undefined

and one warning
warning.js:45 Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See Tabs

Tabs is the component I am using swipeviews.

**Comment by tushartuteja** [comment]
```
  var to = child.props.title.props.to;
```

 this is the line my browser shows error on.

**Comment by damusnet** [comment]
As CaptainN told you previously, the reason all tabs are showing at once is probably because you didn't include the CSS.

As for the error, there is an issue with this lib, that when you have React Router in your project, it expects to find a `to` prop in your titles with a route. If `null` still gives an error, try setting a real value, like `to="#title"`. Do it on all title divs.

The `bind` warning is related to your code `onIndexChange={this._onIndexChange.bind(this)}` ; try setting it to `onIndexChange={this._onIndexChange}` instead.

**Comment by tushartuteja** [comment]
I have added the css. When I give a real value , it shows the following error 
![image](https://cloud.githubusercontent.com/assets/5651179/14523072/53488f5a-024f-11e6-8dc7-3ef14fbd9cee.png)

this is how the page looks
![image](https://cloud.githubusercontent.com/assets/5651179/14523159/d4a1736e-024f-11e6-9f23-e32ffa7718d3.png)

the error is there doesn't matter if I have to={null} or to="#intro".

I have a react router in my main app page.

**Comment by damusnet** [comment]
As per the example, the div should actually be `<div title={<Link to="intro">Intro</Link>}>`

**Comment by tushartuteja** [comment]
I changes the div to the above-mentioned link.

now the following warning and errors are coming.

![image](https://cloud.githubusercontent.com/assets/5651179/14523559/f6843398-0251-11e6-9f1e-26c994f92d5c.png)

**Comment by tushartuteja** [comment]
my url changed to this
http://localhost:8080/#/undefinedfunction search() { [native code] }?_k=undefined

from this

http://localhost:8080/#/0d7a219b-d7bf-4b4a-bc61-c6ae653ef0b5?_k=tmh55h

**Comment by damusnet** [comment]
Which version of React Router are you using?
It is probably not compatible with this lib, and thus causing issues.
This lib was developed with react-router 0.13.2 in mind and I believe their API has changed quite a lot since.

**Comment by tushartuteja** [comment]
I am using 2.0.1.

**Comment by damusnet** [comment]
Yeah so it probably won't work. Sorry about that.
Coupling react-router logic in this lib was a mistake and it should be removed in a future version.
No idea when that's going to happen though.
If you don't need it, I guess you could fork the repo and remove all code associated to react-router like [these lines](https://github.com/damusnet/react-swipe-views/blob/master/src/SwipeViews.js#L106) or [those ones](https://github.com/damusnet/react-swipe-views/blob/master/src/SwipeViews.js#L128).
