### ISSUE TITLE
Failed Context Types:

### ISSUE THREAD

**Issue by sahilCampusdiaries** [damusnet/react-swipe-views#26]
I am trying to use react swipe view in my project. but It is showing these error 
bundle.js:11327Warning: Failed Context Types: Invalid context `router` of type `object` supplied to `SwipeViews`, expected `function`. Check the render method of `Tabs`.

Can you help me to resolve these ?
![error](https://cloud.githubusercontent.com/assets/18225458/15603423/473000fa-2418-11e6-824d-14d2b33a9a12.png)

**Comment by damusnet** [comment]
Hi @sahilCampusdiaries 
These errors are related to `react-router`. Check out [#23](https://github.com/damusnet/react-swipe-views/issues/23#issuecomment-209851507).
Unfortunately this lib is no longer maintained.
Maybe check out [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views)?
