### ISSUE TITLE
ARIA compatible & keyboard navigation

### ISSUE THREAD

**Issue by oyeanuj** [damusnet/react-swipe-views#27]
Hi @damusnet! The plugin looks great, thanks for open sourcing it!

Do you plan to add keyboard navigation and make it ARIA-ready for accessibility?

**Comment by damusnet** [comment]
Hi @oyeanuj, thanks for your kind words.
Unfortunately I stopped maintaining this plugin a while back and for the foreseeable future.
Maybe check out [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views)?
However, I will do my best to try and merge any PR if you wish to contribute.
