### ISSUE TITLE
Routing (react-router) and selectedIndex

### ISSUE THREAD

**Issue by ferrannp** [damusnet/react-swipe-views#3]
First of all thanks for this! It was exactly what I was looking for. I am writing a small web using material-ui and I am hitting all the time the wall with their tabs: http://material-ui.com/#/components/tabs

In order to make this to work with routing, I think it is needed to things: initialSelectedIndex (which the above library just added, so we can route the user when goes to the link directly or refresh the page) and some methodology to keep the tab consistent when the user navigates back and forward (which the library above doesn't handle).

For the first case, it can be handled passing a prop for the initial state (which is not an anti-pattern in this case https://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html)

```
constructor(props) {
  super(props);
  this.state = { 
    selectedIndex: this.props.initialSelectedIndex,
    ...
  };
}
```

For the second case, I am not sure... Here is a pull-request with a proposed solution: https://github.com/jdinard/material-ui/commit/4aad7475877cd3ec425f8b14b009915fda7e8fe8 (but this one looks quite smelly).

**Comment by damusnet** [comment]
Thanks for your input!
Please have a look at #1
It feels like a similar issue.
