### ISSUE TITLE
tab focus passed to non visible views bringing them in focus

### ISSUE THREAD

**Issue by donaldparker** [damusnet/react-swipe-views#30]
My first view is a collection of form elements, the second view is a confirmation page.  However if you press the tab key, you can get the second view to come into the viewable area of the component.

**Comment by damusnet** [comment]
Hi @donaldparker, thanks for your interest in react-swipe-views.
Unfortunately, this component is not maintained anymore.
Maybe have a look at [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views) instead.
