### ISSUE TITLE
The example is not functional in Safari (both desktop and mobile)

### ISSUE THREAD

**Issue by rudin** [damusnet/react-swipe-views#4]
The example works great in Chrome but is not functional in Safari (both desktop and mobile). Might have to do with Babel?
The error says: TypeError: undefined is not a function (evaluating 'Number.isInteger(selectedIndex)')

**Comment by damusnet** [comment]
Nice catch! `Number.isInteger()` is [not supported in Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger) but it is in Chrome and Firefox where I tested the examples. Babel provides a polyfill for [those methods](http://babeljs.io/docs/learn-es6/#math-number-string-object-apis) that can be included [via Browserify or in the Browser](http://babeljs.io/docs/usage/polyfill/). I'll add it in the examples and mention it in the doc.
