### ISSUE TITLE
The swipe views have different height, so the white empty space will be shown on some swipe views. 

### ISSUE THREAD

**Issue by zhangw** [damusnet/react-swipe-views#5]
Hello damusnet:
I tried to use react-swipe-views to build my mobile web page and it worked well in most of time.

But I encountered a problem that if all the swipe views have different height which determined by the contents of themselves and the difference height value between the one view to another view was significant, so there was a large empty space shown on the view which have few content. 

I knew that you used flex property of CSS3 to design the layout ,I thought that it was hard to solve the problem with pure CSS methods if I would still use the flex property as the basis of layout implementation.In consideration of that, I tried to reset the parent of swipe views height value as the current selected swipe view height in the componentDidUpdate callback function but I noticed that the performance seems not good as it caused the div layout repainted.

How do you think about the problem?

**Comment by damusnet** [comment]
Hi,

Every `<div class="SwipeView">` is bound by the `<div class="SwipeViews">` that has a 100% height, and with `overflow-y: scroll`, it allows to scroll inside the div only. That means that one view's height should have no influence on the others.

![image](https://cloud.githubusercontent.com/assets/433409/7731155/c1b0fac0-ff1e-11e4-8cdd-a87b53b61140.png)

Right now I can't reproduce this bug you describe. Can you give me more context like which Browser and OS you use?

**Comment by zhangw** [comment]
Hi damusnet:
I thought the problem is that I put the img elements into each `<div class="SwipeView">` with different amount.

And the height value of `<div class="SwipeViews"`> is equal to the height value of the child element in 
 `<div class="SwipeView">` which has the largest number of images. In my context, the child of second `<div class="SwipeView">` is that one.

According to the img1,img2,img3, it was shown the empty space exists in the first `<div class="SwipeView">`.

It was shown that the height value of `<div class="SwipeViews">` is the same as the child div of the second `<div class="SwipeViews">` according to the img1,img4.

The img5 shows the child element structure which contains text and images.

Looking forward to your reply,thanks!
![img1](https://cloud.githubusercontent.com/assets/196561/7911160/82a4424c-088d-11e5-9343-55c0ccd66a7a.png)
![img2](https://cloud.githubusercontent.com/assets/196561/7911329/2708c2d0-088f-11e5-88c4-4294322ccf56.png)
![img3](https://cloud.githubusercontent.com/assets/196561/7911332/345ff700-088f-11e5-820e-dbe27ac9951e.png)
![img4](https://cloud.githubusercontent.com/assets/196561/7911334/34828c34-088f-11e5-99e9-2c41104ff005.png)
![img5](https://cloud.githubusercontent.com/assets/196561/7911333/34606d52-088f-11e5-944c-3466e898818d.png)

**Comment by damusnet** [comment]
Hello, sorry for not replying sooner. After careful consideration, I believe you should simply set an `height` (or `max-height`) to your `<section id="tabs">` element. The `SwipeView(s)` will spread as much as they can inside the `SwipeViewsContainer` which has a 100% height and needs to be limited. See the `<div id="demo">` of the [demo](http://damusnet.github.io/react-swipe-views/).
