### ISSUE TITLE
Doesn't work on Safari when using Webpack and babel-loader

### ISSUE THREAD

**Issue by dotted** [damusnet/react-swipe-views#6]
When using Webpack and bebel-loader and let babel-loader handle the polyfilling react-swipe-views fails to work because Number.isInteger does not get polyfilled. The reason is that when using Webpack you normally exclude the node_modules folder as it causes a great slow down on the build if webpack has to parse all the files in that folder.

I'm not sure if there exists a solution for this that doesn't involve polluting my app code with polyfilling or adding a special loader for react-swipe-views alone.

For now i did the later by adding this to my webpack loaders:

``` javascript
{ test: /\.(js|jsx)$/, include: /react\-swipe\-views/, loader: 'babel?cacheDirectory&optional[]=runtime' }
```

**Comment by damusnet** [comment]
Have you checked the [npm-wepback example](https://github.com/damusnet/react-swipe-views/tree/362ace1046289e368ce48db83765e0dc301263dc/examples/npm-webpack)? It works by including `babel-core` as a [dependency](https://github.com/damusnet/react-swipe-views/blob/362ace1046289e368ce48db83765e0dc301263dc/examples/npm-webpack/package.json#L9) and doing `require('babel/polyfill');` in [your code](https://github.com/damusnet/react-swipe-views/blob/362ace1046289e368ce48db83765e0dc301263dc/examples/npm-webpack/src/index.js#L9). What's wrong with this approach?

**Comment by dotted** [comment]
As I said, I don't want to pollute my code with polyfills when webpack can handle that for me, and I don't think that I as a developer even should be handling polyfilling for external dependencies at all.

In any case, I'm not sure there is a solution to this other than the ones I already mentioned, it was mostly just to inform you that this was the case for people using babel-loader and webpack for taking care of polyfilling.

**Comment by damusnet** [comment]
But webpack does exactly the same! Adding two lines in your code to make it explicit hardly seems like a big tradeoff to me. Thanks for bringing up the issue, I'll close this ticket for now.

**Comment by dotted** [comment]
Not to drag this on, but as a response to your comment.

If you could guarantee that from now and until the end of time, regardless of what happens in the future, the only polyfill I would have to manually include directly in my code is babel-core, then I would probably just accept that and do it. But that seems like an impossible guarantee so I'm hesitant to even begin doing it because I might need other polyfills in the future and if I simply start including them directly I end up with a big mess, and that's only if it's my own code that has polyfill requirements. If my dependencies start having polyfill requirements as well (as is the case here), it can get pretty hairy, so my rule is simply to say that my code should not have to know about polyfills at all. But its just a personal preference.

I guess it could sort of be analogous to having 2 fully stable libraries 1 is a spaghetti mess behind the scenes and the other is using all the best practices, is SOLID and all that jazz. Sure the spaghetti library works just fine now, but will it keep doing that in the future? Will the spaghetti cause it to no longer be updated in the future because no one wants to touch the code any longer? And while the same concerns applies to the second library, at least I have the option of maintaining myself it while not having to pull my hair out in frustration due to spaghetti.

That's my perspective on it, and it's why i dont want polyfills in my code, I don't think they belong - if I need polyfills I can add them elsewhere (through webpack).

**Comment by damusnet** [comment]
I get your point. What happened in practice is I developed this plugin with ES6 and the latest technologies in mind. Then someone pointed out to me that my use of `Number.isInteger()` broke compatibility with Safari because [reasons](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger#Browser_compatibility). To which the quickest fix seemed to use a polyfill if you needed to support Safari. Which you may or may not according to your particular project. And to document it, which I did. In any case, it is always up to you to check that the dependencies you use are compatible with your target audience. Now you are very welcome to submit a Pull Request to remove `Number.isInteger()` from this library and to avoid the use of a polyfill.

Honestly, the web is a mess, but at least it's a fast moving mess. There is no way anyone can guarantee anything for any period of time beyond a couple of months.

**Comment by topdev423** [comment]
In IE and Safari, We can't find variable: fetch.
How to solve this issue?

**Comment by damusnet** [comment]
Hi @landguy423, as it clearly states [on the readme](https://github.com/damusnet/react-swipe-views#warning-deprecation-notice) of this project, it is not maintained anymore, and you should not use it! That said, `fetch` was [never used](https://github.com/damusnet/react-swipe-views/search?q=fetch&type=Code&utf8=%E2%9C%93) inside this library, and your problem probably comes from somewhere else. In any case, have a look at https://github.com/github/fetch

**Comment by topdev423** [comment]
thanks a lot
